/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supershotgun;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import static supershotgun.GUI.getEnergy;
import static supershotgun.GUI.azione;
import static supershotgun.GUI.yPG;
import static supershotgun.KeyListener.o2;
import static supershotgun.KeyListener.o3;

/**
 *
 * @author Andrea
 */
public class GUI extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form GUI
     */
    private boolean stoped = true;
    private boolean pugno = false;
    private boolean run = false;
    private int life = 100;
    public static int yPG;
    public static JLabel lenergy;    
    static public int energy = 100;
    KeyListener k;
    GUI() throws InterruptedException {
        yPG = 450;
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("SuperShotGun author: Andrea Acanfora");
        k = new KeyListener(l1, l3, l4, l5, l2, car, rock, pontile);      
        this.addKeyListener(k);
        paintComponents(this.getGraphics());
        lenergy=lEnergy;
    }
    public void damage(int damage){
        if(life-damage>0){
            life -=damage;
            lLife.setSize(life*5,20);
            
        }else{
            life = 0;
            lLife.setVisible(false);
        }
        lLife.setText(life+"/100");
    }
    public void recLife(int rec){
        if(life+rec<100){
            life +=rec;
        }else{
            life = 100;        
        }
        lLife.setSize(life*5,20);
        lLife.setText(life+"/100");
    }
    static public int getEnergy(){
        return energy;
    }
    static public void useEnergy(int ener){
        if(energy-ener>0){
            energy -=ener;
            lenergy.setSize(energy*5,20);
            
        }else{
            energy = 0;
        }
        lenergy.setText(energy+"/100");
    }
    public void recEnergy(int ener){
        if(energy+ener<=100){
            energy +=ener;
        }
        lenergy.setSize(energy*5,20);
        lenergy.setText(energy+"/100");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        pontile = new javax.swing.JLabel();
        car = new javax.swing.JLabel();
        rock = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        lLife = new javax.swing.JLabel();
        lEnergy = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(11658, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(11658, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(11658, 1000));
        jPanel1.setLayout(null);

        l2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\SuperShotGun\\pgBiancoFermo.gif")); // NOI18N
        l2.setMaximumSize(new java.awt.Dimension(64, 64));
        l2.setMinimumSize(new java.awt.Dimension(64, 64));
        l2.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(l2);
        l2.setBounds(150, 450, 420, 250);
        jPanel1.add(pontile);
        pontile.setBounds(140, 180, 0, 0);
        jPanel1.add(car);
        car.setBounds(140, 180, 0, 0);
        jPanel1.add(rock);
        rock.setBounds(190, 170, 0, 0);

        l3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\SuperShotGun\\legno.png")); // NOI18N
        jPanel1.add(l3);
        l3.setBounds(0, 150, 1280, 1050);

        l4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\SuperShotGun\\legno.png")); // NOI18N
        jPanel1.add(l4);
        l4.setBounds(1280, 150, 1280, 1050);

        l5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\SuperShotGun\\legno.png")); // NOI18N
        jPanel1.add(l5);
        l5.setBounds(2560, 150, 1280, 1050);

        lLife.setBackground(new java.awt.Color(255, 0, 0));
        lLife.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lLife.setText("100/100");
        lLife.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lLife.setOpaque(true);
        jPanel1.add(lLife);
        lLife.setBounds(20, 20, 500, 20);

        lEnergy.setBackground(new java.awt.Color(255, 204, 0));
        lEnergy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lEnergy.setText("100/100");
        lEnergy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lEnergy.setOpaque(true);
        jPanel1.add(lEnergy);
        lEnergy.setBounds(20, 42, 500, 20);

        l1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrea\\Documents\\NetBeansProjects\\SuperShotGun\\SFONDO2.jpg")); // NOI18N
        jPanel1.add(l1);
        l1.setBounds(0, 0, 11690, 1000);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 11658, 1000);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        GUI g = new GUI();
        Thread t = new Thread(g);
        g.setVisible(true);
        t.start();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel car;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel lEnergy;
    private javax.swing.JLabel lLife;
    private javax.swing.JLabel pontile;
    private javax.swing.JLabel rock;
    // End of variables declaration                   
    static public int azione;
    @Override
    public void run() {
        int sec2 = 0; 
        azione = 0;
        boolean riposiziona = false;
        boolean ridimensiona = false;
        while (true) {            
            try {
                if(sec2 >= 5){
                    recLife(1);
                    sec2 = 0;
                }              
                switch(azione){
                    case 0:
                        l2.setIcon(new javax.swing.ImageIcon("pgBiancoFermo.gif"));
                        recEnergy(1);
                        break;
                    case 1:
                        useEnergy(2);
                        l2.setLocation(120,450);
                        riposiziona = true;
                        l2.setIcon(new javax.swing.ImageIcon("pgMs1.gif"));
                        Thread.sleep(700);
                        azione = 0;
                        break;
                    case 2:
                        l2.setIcon(new javax.swing.ImageIcon("pgBiancoRun.gif"));
                        if(o3.getX()<-2750)
                            riposiziona = true;
                        break;
                    case 3:
                        if((o2.getX()> 250 || o2.getX()<-150))
                            l2.setLocation(150,480);
                        l2.setIcon(new javax.swing.ImageIcon("pgBiancoAbbassato.gif"));
                        break;
                    case 4:
                        useEnergy(4);
                        l2.setIcon(new javax.swing.ImageIcon("pgBiancoAffondo2.gif"));
                        Thread.sleep(500);
                        azione = 0;
                        break;
                    case 5:
                        useEnergy(5);
                        l2.setLocation(50,450);
                        l2.setIcon(new javax.swing.ImageIcon("pgMs5.gif"));
                        Thread.sleep(1000);
                        azione = 0;
                        riposiziona = true;
                        break;
                    case 6:
                        useEnergy(4);
                        l2.setLocation(100,500);
                        riposiziona = true;
                        l2.setIcon(new javax.swing.ImageIcon("pgMs6.gif"));
                        Thread.sleep(500);
                        azione = 0;
                        break;
                    case 7:
                        useEnergy(5);
                        l2.setIcon(new javax.swing.ImageIcon("pgMs7.gif"));
                        Thread.sleep(700);
                        azione = 0;
                        break;
                    case 8:
                        useEnergy(15);
                        l2.setIcon(new javax.swing.ImageIcon("pgMs8.gif"));
                        Thread.sleep(1000);
                        azione = 0;
                        break;
                    case 9:
                        useEnergy(2);
                        l2.setIcon(new javax.swing.ImageIcon("pgBiancoPugnoDestra.gif"));
                        azione = 0;
                        break;    
                    case 10:
                        useEnergy(10);
                        l2.setLocation(25,425);
                        l2.setSize(420,300);
                        riposiziona = true;
                        l2.setIcon(new javax.swing.ImageIcon("pgMsa.gif"));
                        Thread.sleep(1600);
                        ridimensiona = true;
                        azione = 0;
                        break;  
                    case 11:
                        useEnergy(20);
                        l2.setLocation(100,200);
                        l2.setSize(820,600);
                        riposiziona = true;
                        l2.setIcon(new javax.swing.ImageIcon("aaa.gif"));
                        Thread.sleep(4200);                   
                        ridimensiona = true;
                        azione = 0;
                        break; 
                    case 13:
                        useEnergy(15);
                        l2.setLocation(100,450);
                        l2.setIcon(new javax.swing.ImageIcon("colpo.gif"));
                        Thread.sleep(2600); 
                        riposiziona = true;
                        azione = 0;
                        break;
                }
                if(azione == 12){
                    azione = 0;
                    l2.setIcon(new javax.swing.ImageIcon("pgBiancoFermo.gif"));
                    int velo = 1;
                    for(int y = 450; y > 150; y--){       
                        yPG = y;
                        l2.setLocation(150,y);
                        Thread.sleep(velo);
                        if(y == 250)
                            velo++;
                    }
                    for(int y = 150; y < 450; y++){
                        yPG = y;
                        l2.setLocation(150,y);
                        if((o2.getX()<220 && o2.getX()>-180) || (o3.getX()<100 && o3.getX()>-2750 ))
                            break;
                        else
                            Thread.sleep(2);
                    }
                }else{
                    yPG = l2.getY();
                    Thread.sleep(200);
                }
                if(riposiziona){
                    yPG = 450;
                    l2.setLocation(150,450);
                    riposiziona = false;
                }
                if(ridimensiona){
                    l2.setSize(420,250);
                    ridimensiona = false;
                }
                sec2++;
                repaint();
            } catch (InterruptedException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}

class KeyListener extends KeyAdapter {

    private int xSF;
    private int xl1;
    private int xl2;
    private int xl3;
    private final int vel;
    JLabel l;
    JLabel l2;
    JLabel l3;
    JLabel l4;
    JLabel l5;
    JLabel car;
    JLabel rock;
    JLabel pontile;
    Oggetto o;
    public static Oggetto o2,o3;
    public KeyListener(JLabel l, JLabel l2, JLabel l3, JLabel l4, JLabel l5, JLabel car,JLabel rock, JLabel pontile) throws InterruptedException {
        xSF = 0;
        xl1 = 0;
        xl2 = 1280;
        xl3 = 2560;
        vel = 5;
        this.l = l;
        this.l2 = l2;
        this.l3 = l3;
        this.l4 = l4;
        this.l5 = l5;
        this.car = car;   
        this.rock = rock;
        this.pontile = pontile;
        o = new Oggetto(1000,400,426,282,3000,"Car.png",10,car);
        o2 = new Oggetto(580,300,512,512,2500,"rock2.png",3,rock);
        o3 = new Oggetto(500,250,3000,600,5000,"pontile.png",1,pontile);
    }

    public void keyPressed(KeyEvent e) {

        switch (e.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                yPG = l5.getY();
                if (xSF < 0 && (o2.getX()> 240 || o2.getX()<-150 || yPG < 220) ) {
                    l.setLocation(xSF, 0);
                    l2.setLocation(xl1, 150);
                    l3.setLocation(xl2, 150);
                    l4.setLocation(xl3, 150);
                    o.moveX(+vel);
                    o2.moveX(+vel);
                    o3.moveX(+vel);
                    xSF += 1;
                    xl1 += vel ;
                    xl2 += vel ;
                    xl3 += vel ;                 
                    if (xl2 >= 2560) {
                        xl2 -= 3840;
                    }
                    if (xl3 >= 2560) {
                        xl3 -= 3840;
                    }
                }
                break;
            case KeyEvent.VK_RIGHT:
                azione = 2;
                yPG = l5.getY();
                if (xSF > (-11658+1366) && (o2.getX()> 250 || o2.getX()<-150 || yPG < 220)) { // va sottratta la grandezza dello schermo da 11658
                    l.setLocation(xSF, 0);
                    l2.setLocation(xl1, 150);
                    l3.setLocation(xl2, 150);
                    l4.setLocation(xl3, 150);
                    o.moveX(-vel*3);
                    o2.moveX(-vel*3);
                    o3.moveX(-vel*3);
                    xSF -= vel - 3;
                    xl1 -= vel * 3;
                    xl2 -= vel * 3;
                    xl3 -= vel * 3;
                    if (xl1 <= -1280) {
                        xl1 += 3840;
                    }
                    if (xl2 <= -1280) {
                        xl2 += 3840;
                    }
                    if (xl3 <= -1280) {
                        xl3 += 3840;
                    }
                }
                break;
            case KeyEvent.VK_DOWN:
                azione = 3;
                break;
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        super.keyReleased(e); //To change body of generated methods, choose Tools | Templates.
        switch (e.getKeyCode()) {
            case KeyEvent.VK_RIGHT:
                azione = 0;
                break;          
            case KeyEvent.VK_P:
                if(getEnergy()>=2){
                    azione = 1;
                }
                break;
            case KeyEvent.VK_DOWN:
                azione = 0;
                if((o2.getX()> 250 || o2.getX()<-150)){
                    yPG = 450;
                    l5.setLocation(150, 450);
                }
                break;
            case KeyEvent.VK_O:
                if(getEnergy()>=4){
                    azione = 4;
                }
                break;
            case KeyEvent.VK_Q:
                if(getEnergy()>=5){
                    azione = 5;
                }
                break;
            case KeyEvent.VK_W:
                if(getEnergy()>=4){
                    azione = 6;
                }
                break;
            case KeyEvent.VK_E:
                if(getEnergy()>=5){
                    azione = 7;
                }
                break;
            case KeyEvent.VK_T:
                if(getEnergy()>=15){
                    azione = 8;
                }
                break;
            case KeyEvent.VK_I:
                if(getEnergy()>=2){
                    azione = 9;
                }
                break;
            case KeyEvent.VK_R:
                if(getEnergy()>=10){
                    azione = 10;
                }
                break;
            case KeyEvent.VK_Y:
                if(getEnergy()>=20){
                    azione = 11;
                }
                break;
            case KeyEvent.VK_UP:
                azione = 12;
                break;
            case KeyEvent.VK_U:
                if(getEnergy()>=15){
                    azione = 13;
                }
                break;
        }
    }

}
